load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# v1.0.1 is the earliest verson supporting Bazel 5.
# Always use the latest version available.
http_archive(
    name = "rules_s3",
    urls = ["https://github.com/tweag/rules_s3/releases/download/v1.0.1/rules_s3-v1.0.1.tar.gz"],
    sha256 = "fcb740c7436035b46e94f54b4cb82d5336ed661cf3f3b7bec066c9e06122e06f",
    strip_prefix = "rules_s3-1.0.1",
)
local_repository(
    name = "rules_s3",
    path = "../..",
)

load("@rules_s3//s3:repo_rules.bzl", "s3_archive", "s3_file")

# Note: s3_bucket.from_file is a module extension, which doesn't work out of the box with Bazel 5.
# You can use s3_file and s3_archive to fetch individual files and archives from a bucket.

s3_archive(
    name = "kubernetes_1_30_3",
    build_file_content = """exports_files(glob(["**"]))""",
    integrity = "sha256-9x9WRt4Xw8n3IgE9T1PlChVoInD1YXrAYdQw6moWAM0=",
    strip_prefix = "kubernetes",
    url = "s3://malte-s3-public-test/release/v1.30.3/kubernetes.tar.gz",
    endpoint = "s3.eu-north-1.amazonaws.com",
)

s3_file(
    name = "k8s_1_30_2_release_notes",
    sha256 = "e879f76b7bac8effe4cc53bce034f258ce15b2825f3018c7078f25e832c3feb8",
    url = "s3://malte-s3-public-test/release/v1.30.2/release-notes.json",
    endpoint = "s3.eu-north-1.amazonaws.com",
)
